### PR TITLE
Add request header for media downloads

### PR DESCRIPTION
**Pull request by dklimpel**
Add options to set and configure HTTP request headers for the download
requests of mcs from homeserver
- user-agent
- x-forwarded-for

### CODE REVIEW

**Comment by dklimpel** [comment]
Do you have a hint to the error at CI/CD?
I am get also the same error with current master.

**Comment by dklimpel** [comment]
At this moment the tests are successful. It seems to be due to the combination of the reaction or download time of matrix.org and the timeouts in the tests.

**Review by babolivier — CHANGES_REQUESTED** [review]
Hey, and sorry it took us so long to look at your PR.
It looks like the CI is failing for unrelated reasons, I've opened https://github.com/matrix-org/matrix-content-scanner/pull/38 to fix it.
Now that it's merged, could you please merge master into your branch and write a test for your feature?

**Comment by dklimpel** [comment]
I have tried to create tests. But I am not a NodeJS expert. I did not succeed. Neither a unit test only on the one function `generateRequestHeaders` nor a full request. To test a full request I don't know how to catch the request from the content scanner to the matrix server to check the headers.
For this tests I am need help or a hint.

**Review by babolivier — APPROVED** [review]
Sorry for taking so long to come back to this. Since it's a small change, it might not be worth the trouble writing a test for it just now, so I'm going to merge it.

**Pull request merged**
